# https://github.com/aws-actions/configure-aws-credentials
# https://github.com/aws-actions/amazon-ecr-login

on: push

jobs:
  deploy:
    name: Upload to Amazon ECR

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/role-with-oidc
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR Public
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Shorten hash
        id: shorten_hash
        shell: bash
        run: echo "##[set-output name=hash;]${GITHUB_SHA::7}"

      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: myapp
          IMAGE_TAG: ${{ steps.shorten_hash.outputs.hash }}
        run: |
          docker buildx build -t "$REGISTRY/$REPOSITORY:$IMAGE_TAG" .
          docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
        working-directory: app
